/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package biomauth;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.TargetDataLine;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AudioLogin extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public static int uidt;
    public static boolean audioVal;
    public static int audioid;
    
    public AudioLogin() {
        initComponents();
        //audioPanel.setVisible(false);
        nextKeyBut.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        audioPanel = new javax.swing.JPanel();
        msgText = new javax.swing.JLabel();
        msgImage = new javax.swing.JLabel();
        nextKeyBut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        uidText = new javax.swing.JTextField();
        nextBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 247, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 130, 90));

        audioPanel.setBackground(new java.awt.Color(245, 247, 249));
        audioPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgText.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        msgText.setText("Say 'Hello'");
        audioPanel.add(msgText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 120, 50));

        msgImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biomauth/images/Picture2.png"))); // NOI18N
        audioPanel.add(msgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 620, 170));

        nextKeyBut.setBackground(new java.awt.Color(255, 153, 153));
        nextKeyBut.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        nextKeyBut.setForeground(new java.awt.Color(255, 255, 255));
        nextKeyBut.setText("Next");
        nextKeyBut.setContentAreaFilled(false);
        nextKeyBut.setOpaque(true);
        nextKeyBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextKeyButActionPerformed(evt);
            }
        });
        audioPanel.add(nextKeyBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 140, 50));

        jPanel1.add(audioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 710, 310));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel3.setText("User ID ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 80, 50));

        uidText.setBackground(new java.awt.Color(245, 247, 249));
        uidText.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        uidText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uidText.setToolTipText("Enter your userID number");
        uidText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 5));
        jPanel1.add(uidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 360, 60));

        nextBut.setBackground(new java.awt.Color(255, 153, 153));
        nextBut.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        nextBut.setForeground(new java.awt.Color(255, 255, 255));
        nextBut.setText("Next");
        nextBut.setContentAreaFilled(false);
        nextBut.setOpaque(true);
        nextBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButActionPerformed(evt);
            }
        });
        jPanel1.add(nextBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextKeyButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextKeyButActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TypeLogin().setVisible(true);
        
    }//GEN-LAST:event_nextKeyButActionPerformed

    private void nextButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButActionPerformed
        //audioPanel.setVisible(true);
        JOptionPane.showMessageDialog(this, "Recording starts ..");
        
        try {
            recordSound("testau34.wav");
            JOptionPane.showMessageDialog(this, "Recording finished ..");
            Thread.sleep(3000);
            nextBut.setVisible(false);
            msgText.setText("Processing .. ");
            msgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biomauth/images/d_helix-css-gif-_50fps-selective_-1a.gif")));
            double[] data = DFT.getData("testau34.wav");
            Thread.sleep(3000);
            uidt = Integer.parseInt(uidText.getText());
            int id=DFT.classifyData(data[0], data[1]);
            audioid=id;
            if(id==uidt){
                audioVal=true;
            }else{
                audioVal=false;
            }
            nextKeyBut.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AudioLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AudioLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AudioLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WavFileException ex) {
            Logger.getLogger(AudioLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(AudioLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextButActionPerformed

    public void recordSound(final String fname) {
        final AudioFormat audioFormat = new AudioFormat(16000, 8, 2, true, true);
        final DataLine.Info info = new DataLine.Info(TargetDataLine.class, audioFormat);

        if (!AudioSystem.isLineSupported(info)) {
            System.out.println("Line not supported");
        }
        try {
            final TargetDataLine line = (TargetDataLine) AudioSystem.getLine(info);
            line.open();
            System.out.println("recording starts");
            line.start();

            Thread stopping = new Thread(new Runnable() {
                @Override
                public void run() {
                    AudioInputStream st = new AudioInputStream(line);
                    File wf = new File(fname);
                    System.out.println(st.getFrameLength());
                    try {
                        AudioSystem.write(st, AudioFileFormat.Type.WAVE, wf);
                    } catch (IOException ex) {
                        ex.printStackTrace();
                        //JOptionPane.showMessageDialog(rootPane, "File writing interrupted ..");
                    }
                }
            });

            stopping.start();
            Thread.sleep(1500);
            line.stop();
            line.close();
            System.out.println("Ended");

        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(rootPane, "File writing interrupted ..");
        } catch (LineUnavailableException ex) {
            JOptionPane.showMessageDialog(rootPane, "Stream unvaliable ..");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudioLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudioHome().setVisible(true);
            }
        });*/
        
        new AudioLogin().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel audioPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msgImage;
    private javax.swing.JLabel msgText;
    private javax.swing.JButton nextBut;
    private javax.swing.JButton nextKeyBut;
    private javax.swing.JTextField uidText;
    // End of variables declaration//GEN-END:variables
}
