/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package biomauth;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TypeHome extends javax.swing.JFrame {

    /**
     * Creates new form TypeHome
     */
    private ArrayList<Long> kp;
    private ArrayList<Long> kl;
    public TypeHome() {
        initComponents();
        
        kp=new ArrayList<>();
        kl=new ArrayList<>();
        
        nextBut.setVisible(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        msgText = new javax.swing.JLabel();
        typeText = new javax.swing.JTextField();
        nextBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 247, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(245, 247, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setText("Type the text");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 370, 90));

        msgText.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        msgText.setText("We wil be able to recognize you way better next time");
        jPanel2.add(msgText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 480, 50));

        typeText.setBackground(new java.awt.Color(245, 247, 249));
        typeText.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        typeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        typeText.setText("Type here");
        typeText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 5));
        typeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeTextMouseClicked(evt);
            }
        });
        typeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTextActionPerformed(evt);
            }
        });
        typeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                typeTextFocusGained(evt);
            }
        });
        typeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                typeTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                typeTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                typeTextKeyTyped(evt);
            }
        });
        jPanel2.add(typeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 620, 60));

        nextBut.setBackground(new java.awt.Color(255, 153, 153));
        nextBut.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        nextBut.setForeground(new java.awt.Color(255, 255, 255));
        nextBut.setText("Done");
        nextBut.setToolTipText("");
        nextBut.setContentAreaFilled(false);
        nextBut.setOpaque(true);
        nextBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButActionPerformed(evt);
            }
        });
        jPanel2.add(nextBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 140, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButActionPerformed
        // TODO add your handling code here:
        long val=0;
        long avg=0;
        //Dwell time calculation
        for(int i=0;i<kl.size();i++){
            val+=kl.get(i)-kp.get(i);
        }
        avg+=val/kl.size();
        System.out.println("Dwell time/Avg : "+val/kl.size());
        
        //Interval calculation
        val=0;
        for(int i=0;i<kl.size()-1;i++){
            val+=kp.get(i+1)-kl.get(i);
        }
        avg+=val/(kl.size()-1);
        System.out.println("Interval : "+val/(kl.size()-1));
        
        //Latency calculation
        val=0;
        for(int i=0;i<kl.size()-1;i++){
            val+=kl.get(i+1)-kp.get(i);
        }
        avg+=val/(kl.size()-1);
        System.out.println("Latency : "+val/(kl.size()-1));
        
        //Flight time calculation
        val=0;
        for(int i=0;i<kp.size()-1;i++){
            val+=kp.get(i+1)-kp.get(i);
        }
        avg+=val/(kl.size()-1);
        System.out.println("Flight time : "+val/(kp.size()-1));
        
        //Up to up time calculation
        val=0;
        for(int i=0;i<kl.size()-1;i++){
            val+=kl.get(i+1)-kl.get(i);
        }
        avg+=val/(kl.size()-1);
        System.out.println("Up to up : "+val/(kl.size()-1));
        
        try {
            int rstv=writeData(Home.uidft, avg/5);
            if(rstv>0){
                JOptionPane.showMessageDialog(this, "Successfully signed up ..");
                this.dispose();
                new AuthHome().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Sign up faild, Try again  ..");
                this.dispose();
                new AuthHome().setVisible(true);
            }
            
        } catch (SQLException ex) {
            
        }

    }//GEN-LAST:event_nextButActionPerformed

    private void typeTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typeTextFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_typeTextFocusGained

    private void typeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeTextMouseClicked
        // TODO add your handling code here:
        //typeText.setText("");
    }//GEN-LAST:event_typeTextMouseClicked

    private void typeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeTextKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_typeTextKeyTyped

    private void typeTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeTextKeyPressed
        // TODO add your handling code here:
        Date d=new Date();
        long time = d.getTime();
        kp.add(time);
        
    }//GEN-LAST:event_typeTextKeyPressed

    private void typeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeTextKeyReleased

        String tyt=typeText.getText();
        if(tyt.equals("We will be able to recognize you way better next time")){
            System.out.println("done");
            nextBut.setVisible(true);
        }
        
        Date d=new Date();
        long time = d.getTime();
        kl.add(time);
        
    }//GEN-LAST:event_typeTextKeyReleased

    private void typeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TypeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TypeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TypeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TypeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TypeHome().setVisible(true);
                
            }
        });
    }
    
    public static int writeData(int uid, double avg) throws SQLException {
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/User_Info", "senuri", "123");
        PreparedStatement prepareStatement = con.prepareStatement("Insert into KeyDy values(?,?) ");
        prepareStatement.setDouble(1, uid);
        prepareStatement.setDouble(2, avg);
        int executeUpdate = prepareStatement.executeUpdate();
        return executeUpdate;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel msgText;
    private javax.swing.JButton nextBut;
    private javax.swing.JTextField typeText;
    // End of variables declaration//GEN-END:variables
}
